version: '3.8'

services:
  app:
    container_name: my-app
    image: my-image   
    build:
      context: .
      dockerfile: Dockerfile
    ports:


      - "8081:3000"
    volumes:
      - .:/app
    command: npm start

