name: Docker CI/CD 

on:
  push:
    branches:
      - main

jobs:
 
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and test 
        run: |
          docker build -t nodejs-basic .
          docker run nodejs-basic npm test

      - name: Push image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nodejs-basic:${{ github.sha }}

  deploy:
    needs: build_and_test
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Pull image mà được push lên DockerHub bên trên
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/nodejs-basic:${{ github.sha }}

            # Dừng và gỡ bỏ container hiện tại (nếu có)
            docker stop nodejs-container
            docker rm nodejs-container 

            # Chạy container mới với image đã pull về bên trên
            docker run -d -p 80:3000 --name nodejs-container ${{ secrets.DOCKERHUB_USERNAME }}/nodejs-basic:${{ github.sha }}


